import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Al-Noor MSA",
  description:
    "Bring together the entire Muslim community and guide it in a direction where we can grow together in the path of Allah.Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
